name: esc-action
description: GitHub Action to install the ESC CLI and inject environment variables from an ESC environment.
branding:
  icon: unlock
  color: purple
author: Pulumi
inputs:
  version:
    description: 'Version of ESC CLI to install. If omitted, installs the latest.'
    required: false
    default: ''
  environment:
    description: 'The ESC environment to pull environment variables from.'
    required: false
    default: ''
  keys:
    description: 'A comma-separated list of specific keys to inject from within the ESC values.environmentVariables object. E.g. "NPM_TOKEN,SLACK_WEBHOOK_URL".'
    required: false
    default: ''
  cloud-url:
    description: 'The URL of the Pulumi Cloud API. Defaults to https://api.pulumi.com.'
    required: false
    default: ''
  export-environment-variables:
    description: "Whether or not to export environment variables. All environment variables will always be available in the 'env' step output."
    required: false
  oidc-auth:
    description: 'When true, the ESC action will exchange the GitHub workflow OIDC token for a Pulumi Access Token. Requires id-token: write permission.'
    required: false
    default: 'false'
  oidc-organization:
    description: 'The name of the Pulumi organization to use for OIDC token exchange. Required if oidc-auth is true.'
    required: false
    default: ''
  oidc-requested-token-type:
    description: 'The type of Pulumi Access Token to obtain. Required if oidc-auth is true.'
    required: false
    default: ''
  oidc-scope:
    description: 'The requested scopes for the Pulumi Access Token.'
    required: false
    default: ''
  oidc-token-expiration:
    description: 'The time-to-live for the Pulumi Access Token.'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
