on: [push]

jobs:
  test-env-injection:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install and inject ESC environment variables
        uses: ./
        with:
          environment: 'pulumi/imports/github-secrets'
        env:
          # If needed, set your Pulumi access token or other secrets
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN_PRODUCTION }}

      - name: Verify injection
        run: |
          echo "Testing env injection..."
          echo "NPM_TOKEN=$NPM_TOKEN"
