on:
  - pull_request
permissions:
  id-token: write
  contents: read

jobs:
  test-cli-download-only:
    strategy: {matrix: {os: [ubuntu-latest, windows-latest]}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install ESC CLI
        uses: ./
      - name: Verify CLI exists
        run: esc version
  test-cli-download-specific-version:
    strategy: {matrix: {os: [ubuntu-latest, windows-latest]}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install ESC CLI
        uses: ./
        with:
          version: '0.10.0'
      - name: Verify CLI exists
        run: esc version
  test-individual-keys:
    strategy: {matrix: {os: [ubuntu-latest]}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Authenticate with Pulumi Cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: pulumi
          requested-token-type: urn:pulumi:token-type:access_token:organization
          cloud-url: https://api.pulumi-staging.io
      - name: Install ESC and open an environment
        id: esc
        uses: ./
        with:
          environment: 'pulumi/github/esc-action'
          keys: 'FOO,SOME_IMPORTANT_KEY'
          cloud-url: https://api.pulumi-staging.io
          export-environment-variables: false
      - name: Verify injection
        run: |
          echo "Testing env injection..."
          REQUIRED_VARS=("K1" "K2")
          for var in "${REQUIRED_VARS[@]}"; do
            if [[ -z "${!var}" ]]; then
              echo "Error: $var is not set or empty" >&2
              exit 1
            fi
            echo "$var is set to: ${!var}"
          done
          if [[ -n $(env | grep "^\(FOO\|SOME_IMPORTANT_KEY\|TEST_ENV\)=") ]]; then
            echo "Error: unexpected variables are set" >&2
            env
            exit 1
          fi
        env:
          K1: ${{ steps.esc.outputs.FOO }}
          K2: ${{ steps.esc.outputs.SOME_IMPORTANT_KEY }}
  test-all-keys:
    strategy: {matrix: {os: [ubuntu-latest]}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Authenticate with Pulumi Cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: pulumi
          requested-token-type: urn:pulumi:token-type:access_token:organization
          cloud-url: https://api.pulumi-staging.io
      - name: Install ESC and open an environment
        id: esc
        uses: ./
        with:
          # This action uses the https://app.pulumi-staging.io/pulumi/esc/github/esc-action environment
          environment: 'pulumi/github/esc-action'
          cloud-url: https://api.pulumi-staging.io
          export-environment-variables: false
      - name: Verify injection
        run: |
          echo "Testing env injection..."
          REQUIRED_VARS=("K1" "K2" "K3")
          for var in "${REQUIRED_VARS[@]}"; do
            if [[ -z "${!var}" ]]; then
              echo "Error: $var is not set or empty" >&2
              exit 1
            fi
            echo "$var is set to: ${!var}"
          done
          if [[ -n $(env | grep "^\(FOO\|SOME_IMPORTANT_KEY\|TEST_ENV\)=") ]]; then
            echo "Error: unexpected variables are set" >&2
            env
            exit 1
          fi
        env:
          K1: ${{ steps.esc.outputs.FOO }}
          K2: ${{ steps.esc.outputs.SOME_IMPORTANT_KEY }}
          K3: ${{ steps.esc.outputs.TEST_ENV }}
  test-individual-key-injection:
    strategy: {matrix: {os: [ubuntu-latest]}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Authenticate with Pulumi Cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: pulumi
          requested-token-type: urn:pulumi:token-type:access_token:organization
          cloud-url: https://api.pulumi-staging.io
      - name: Inject only specific environment variables
        id: esc
        uses: ./
        with:
          environment: 'pulumi/github/esc-action'
          keys: 'FOO,SOME_IMPORTANT_KEY'
          cloud-url: https://api.pulumi-staging.io
      - name: Verify injection
        run: |
          echo "Testing env injection..."
          REQUIRED_VARS=("FOO" "SOME_IMPORTANT_KEY")
          for var in "${REQUIRED_VARS[@]}"; do
            if [[ -z "${!var}" ]]; then
              echo "Error: $var is not set or empty" >&2
              exit 1
            fi
            echo "$var is set to: ${!var}"
          done
          if [[ -n $(env | grep "^TEST_ENV=") ]]; then
            echo "Error: unexpected variables are set" >&2
            env
            exit 1
          fi
  test-envvars-individual-key-injection:
    strategy: {matrix: {os: [ubuntu-latest]}}
    runs-on: ${{ matrix.os }}
    env:
      ESC_ACTION_ENVIRONMENT: pulumi/github/esc-action
      ESC_ACTION_KEYS: FOO,SOME_IMPORTANT_KEY
      ESC_ACTION_CLOUD_URL: https://api.pulumi-staging.io
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Authenticate with Pulumi Cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: pulumi
          requested-token-type: urn:pulumi:token-type:access_token:organization
          cloud-url: https://api.pulumi-staging.io
      - name: Install and inject ESC environment variables
        uses: ./
      - name: Verify injection
        run: |
          echo "Testing env injection..."
          REQUIRED_VARS=("FOO" "SOME_IMPORTANT_KEY")
          for var in "${REQUIRED_VARS[@]}"; do
            if [[ -z "${!var}" ]]; then
              echo "Error: $var is not set or empty" >&2
              exit 1
            fi
            echo "$var is set to: ${!var}"
          done
          if [[ -n $(env | grep "^TEST_ENV=") ]]; then
            echo "Error: unexpected variables are set" >&2
            env
            exit 1
          fi
  test-all-key-injection:
    strategy: {matrix: {os: [ubuntu-latest]}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Authenticate with Pulumi Cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: pulumi
          requested-token-type: urn:pulumi:token-type:access_token:organization
          cloud-url: https://api.pulumi-staging.io
      - name: Install and inject ESC environment variables
        uses: ./
        with:
          # This action uses the https://app.pulumi-staging.io/pulumi/esc/github/esc-action environment
          environment: 'pulumi/github/esc-action'
          cloud-url: https://api.pulumi-staging.io
      - name: Verify injection
        run: |
          echo "Testing env injection..."
          REQUIRED_VARS=("FOO" "SOME_IMPORTANT_KEY" "TEST_ENV")
          for var in "${REQUIRED_VARS[@]}"; do
            if [[ -z "${!var}" ]]; then
              echo "Error: $var is not set or empty" >&2
              exit 1
            fi
            echo "$var is set to: ${!var}"
          done
