on: [push]

jobs:
  test-cli-download-only:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install ESC CLI
        uses: ./
      - name: Verify CLI exists
        run: esc version
  test-cli-download-specific-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install ESC CLI
        uses: ./
        with:
          version: '0.10.0'
      - name: Verify CLI exists
        run: esc version
  test-individual-key-injection:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Inject only specific environment variables
        uses: ./
        with:
          environment: 'pulumi/imports/github-secrets'
          keys: 'NPM_TOKEN,PULUMI_BOT_TOKEN'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN_PRODUCTION }}
      - name: Verify injection
        run: |
          echo "Testing env injection..."
          echo "NPM_TOKEN=$NPM_TOKEN"
          echo "PULUMI_BOT_TOKEN=$PULUMI_BOT_TOKEN"
  test-all-key-injection:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install and inject ESC environment variables
        uses: ./
        with:
          environment: 'pulumi/imports/github-secrets'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN_PRODUCTION }}
      - name: Verify injection
        run: |
          echo "Testing env injection..."
          echo "NPM_TOKEN=$NPM_TOKEN"
          echo "PULUMI_BOT_TOKEN=$PULUMI_BOT_TOKEN"
          echo "COVERAGE_OUTPUT_DIR=$COVERAGE_OUTPUT_DIR"
